EmployeeManagement/Controllers/RoleanduserController.cs
using EmployeeManagement.Migrations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagement.Controllers
{
    //[AllowAnonymous]
    public class RoleanduserController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<EmployeeManagement.Models.ApplicationUser> usermanager;

        public RoleanduserController(RoleManager<IdentityRole> roleManager , UserManager<EmployeeManagement.Models.ApplicationUser> _usermanager)
        {
            this.roleManager = roleManager;
            this.usermanager = _usermanager;
        }

        //[Authorize(Roles = "systemAdminsitrator")] // user or systemAdminsitrator
        //[Authorize(Roles = "systemAdminsitrator")][Authorize(Roles = "user")] // user and systemAdminsitrator
        public async Task<String> all()
        {
            String _user = "";

            foreach (var user in usermanager.Users)
            {
                _user += user.Id + " : " + user.Email + "\n";
            }
            return _user;
        }

        [Authorize(Roles = "systemAdminsitrator")]
        public async Task<String> index(String roleName)
        {
            String _user= "";
            var role = await roleManager.FindByNameAsync(roleName);
            if (role == null)
            {
                return "error ,No Role Name";
            }
            var users = await usermanager.GetUsersInRoleAsync(roleName);
            foreach (var user in users)
            {
                _user += user.Id + " : " + user.Email + "\n";
            }
            return _user;
        }
        public async Task<String> addUserToRole()
        {
            //String userId = "08ae6a08-83f6-4579-a960-a2d589bc9e97";

            String userId = "c5a9936a-40c0-4a2a-88ff-3b3e4d6076c5";
            var user = await usermanager.FindByIdAsync(userId);
            await usermanager.AddToRoleAsync(user, "systemAdminsitrator");
            //userId = "850c8d44-8f82-4c2e-b39f-e51583f6be11";
            //user = await usermanager.FindByIdAsync(userId);
            //await usermanager.AddToRoleAsync(user, "systemAdminsitrator");
            return "added";
        }
        public async Task<String> RomoveUsersInRole()
        {
            var userId = "850c8d44-8f82-4c2e-b39f-e51583f6be11";
            var user = await usermanager.FindByIdAsync(userId);
            if (await usermanager.IsInRoleAsync(user, "systemAdminsitrator")) { 
            
                await usermanager.RemoveFromRoleAsync(user, "systemAdminsitrator");
            }

            return "test";
        }


        public async Task<String> editUser()
        {
            var userId = "850c8d44-8f82-4c2e-b39f-e51583f6be11";
            var usr = await usermanager.FindByIdAsync(userId);
            usr.Email = "superAdmin@gmail.com";
            await usermanager.UpdateAsync(usr);
            return "edit";
        }



        public async Task<String> deleteRole()
        {
            var role = await roleManager.FindByNameAsync("admin");
            await roleManager.DeleteAsync(role);
            return "delete";
        }

        public async Task<String> deleteUser()
        {
            var userId = "9e6927c8-a0a0-4076-889a-0407e24f58af";
            var usr = await usermanager.FindByIdAsync(userId);
            usr.Email = "superAdmin@gmail.com";
            await usermanager.DeleteAsync(usr);
            return "delete";
        }


        public async Task<String> getUserRoles() {
            string roles = "";
            //String userId = "08ae6a08-83f6-4579-a960-a2d589bc9e97";
            String userId = "c5a9936a-40c0-4a2a-88ff-3b3e4d6076c5";

            var user = await usermanager.FindByIdAsync(userId);
            var _roles = await usermanager.GetRolesAsync(user);
            foreach (var role in _roles)
            {
                roles += role + "\n";
            }
            return roles;
        }
    }
}

EmployeeManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmployeeManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">EmployeeManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>

                        @if (usr.IsSignedIn(User))
                        {
                            
                            @if (User.IsInRole("systemAdminsitrator"))
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Roleanduser" asp-action="index" asp-route-roleName="systemAdminsitrator">Admins</a>
                                </li>
                            }
                            

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Roleanduser" asp-action="all">users</a>
                            </li>
                    }

                    </ul>
                </div>
                <div class="float-right">
                    @if (!(usr.IsSignedIn(User)))
                    {
                        
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="login">Login</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="profile">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="logout">Logout</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EmployeeManagement - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>